Fix compiler error by using es2018 to use 'AsyncGenerator'. node_modules/keyv/src/index.d.ts:60:32 - error TS2583: Cannot find name 'AsyncGenerator'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2018' or later.
60  iterator(namespace?: string): AsyncGenerator<any, void, any>;
                                  ~~~~~~~~~~~~~~

Found 1 error in node_modules/keyv/src/index.d.ts:60